### ISSUE TITLE
e.chnls

### ISSUE THREAD

**Issue by MargPerry** [msschwartz21/craniumPy#28]
When using cranium and running the code 
`genthresh=0.5
scale=[1,1,1]
microns=[0.16,0.16,0.21]
e.chnls['AT'].preprocess_data(genthresh,scale,microns)`
 we get the error tuple index out of range 
with the lines 4, 163, 76 pointed out.

**Comment by msschwartz21** [comment]
There's not enough information to reproduce this issue. It could be the result of trying to load the wrong type of data file.
