### ISSUE TITLE
PCA Implementation

### ISSUE THREAD

**Issue by msschwartz21** [msschwartz21/craniumPy#6]
Use PCA to align data to a normalized set of axes

Scale xyz by set scalars to ensure that the general primary, secondary, and tertiary axes are consistent

**Comment by msschwartz21** [comment]
Does PCA change the relative distance between points e.g. does it change the scale of the data?

**Comment by msschwartz21** [comment]
Is there a way to take the PCA alignment calculated for one dataset and apply it to another?

**Comment by beanumber** [comment]
It should not change the relative distance of the points, since the result is just a rotation matrix. 

That rotation matrix could be used to then rotate another set of data.
